export const MILESTONE_CONSTANTS = {
  DEFAULT_CONTRACT_PERIOD_DAYS: 7,
  MAX_CONTRACT_PERIOD_DAYS: 30,
  MIN_CONTRACT_PERIOD_DAYS: 1,
  DEFAULT_MILESTONE_ALLOCATION: 0.1, // BTC
  MAX_MILESTONE_ALLOCATION: 10, // BTC
  DEFAULT_COIN_TYPE: 'ckbtc',
} as const;

export const MILESTONE_FREQUENCIES = {
  DAY_1: 'day-1',
  DAY_15: 'day-15',
  DAY_28: 'day-28',
} as const;

export const MILESTONE_VALIDATION = {
  MIN_ALLOCATION: 0.00000001,
  MAX_ALLOCATION: 10,
  MIN_SHARE: 0,
  MAX_SHARE: 100,
} as const;
