"use client";

import TransactionStats from "@/components/TransactionStats";
import { Button } from "@/components/ui/button";
import { Typography } from "@/components/ui/typography";
import { EditEscrowDetailsProps } from "@/modules/shared.types";
import { motion } from "framer-motion";
import { CircleAlert, Edit, Shield } from "lucide-react";
import { calculateTotalBTC, countUniqueRecipients } from "../../utils/transactionDetailsHelpers";

export default function EditEscrowDetails({
  transaction,
  onCancel,
  onEdit,
  isLoading = false
}: EditEscrowDetailsProps) {
  console.log('🔍 EditEscrowDetails Debug:', {
    hasOnCancel: !!onCancel,
    hasOnEdit: !!onEdit,
    onCancelType: typeof onCancel,
    onEditType: typeof onEdit,
    isLoading,
    transactionId: transaction.id
  });

  const totalBTC = calculateTotalBTC(transaction);

  const recipientCount = countUniqueRecipients(transaction);

  return (
    <div className="container !rounded-2xl !p-6">

      <Typography variant="large" className="mb-4">Escrow overview</Typography>

      <TransactionStats
        totalBTC={totalBTC}
        recipientCount={recipientCount}
        status={transaction.status}
      />


      <hr className="my-6 text-[#424444] h-[1px]" />

      <Typography variant="large" className="text-[#FEB64D]">Funding required</Typography>

      {/* Warning Banner */}
      <div className="bg-[#48351A] border border-[#BD822D] rounded-[10px] p-4 mt-4">
        <div className="flex items-start space-x-3">
          <CircleAlert className="w-5 h-5 text-[#FEB64D] mt-0.5 flex-shrink-0" />
          <div className="space-y-2">
            <Typography variant="base" className="text-[#FEB64D] font-semibold">
              Send exactly {totalBTC.toFixed(8)} BTC to activate escrow
            </Typography>
            <Typography variant="small" className="text-white">
              This address is generated by ICP threshold ECDSA — no bridges, no wrap
            </Typography>
          </div>
        </div>
      </div>


      <div className="container-gray mt-6">
        <div className="flex items-start gap-3">
          <span className="bg-[#4F3F27] p-2 rounded-full">
            <Shield color="#FEB64D" />
          </span>
          <div>
            <Typography variant="base" className="text-white font-semibold">
              Fully Trustless
            </Typography>
            <Typography className="text-[#9F9F9F] mt-1">
              Escrow powered by Internet Computer&apos;s native Bitcoin integration.
              No bridge. No wrap. Fully trustless.
            </Typography>
          </div>
        </div>
      </div>

      <hr className="my-8 text-[#424444] h-[1px]" />

      {(() => {
        const shouldShowButtons = transaction.status === "pending" && !transaction.releasedAt && (onCancel || onEdit);
        console.log('🔍 Button Container Condition Debug:', {
          transactionStatus: transaction.status,
          isPending: transaction.status === "pending",
          releasedAt: transaction.releasedAt,
          isNotReleased: !transaction.releasedAt,
          hasOnCancel: !!onCancel,
          hasOnEdit: !!onEdit,
          hasEitherFunction: !!(onCancel || onEdit),
          shouldShowButtons
        });
        return shouldShowButtons;
      })() && (
        <motion.div
          className="flex items-center gap-3 mt-4"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          {(() => {
            // Check if any recipients have taken action
            const hasRecipientAction = transaction.to?.some((recipient) =>
              recipient.status && Object.keys(recipient.status)[0] !== "pending"
            ) || false;

            console.log('🔍 Edit Button Condition Debug:', {
              hasRecipientAction,
              hasOnEdit: !!onEdit,
              recipients: transaction.to,
              recipientStatuses: transaction.to?.map(r => r.status),
              shouldShowEdit: !hasRecipientAction && onEdit
            });

            return onEdit; // TEMPORARY: Remove hasRecipientAction condition
          })() && (
              <motion.div
                whileTap={{ scale: 0.95 }}
                transition={{ duration: 0.1 }}
              >
                <Button
                  className="bg-[#FEB64D] text-black hover:bg-[#FEB64D]/90 font-semibold h-10"
                  onClick={onEdit}
                  disabled={isLoading === "edit"}
                >
                  {isLoading === "edit" ? (
                    <svg
                      className="animate-spin h-4 w-4 mr-2"
                      viewBox="0 0 24 24"
                    >
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                        fill="none"
                      />
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8v8z"
                      />
                    </svg>
                  ) : (
                    <Edit size={16} className="mr-2" />
                  )}
                  {isLoading === "edit" ? "Editing..." : "Edit escrow"}
                </Button>
              </motion.div>
            )}
          {onCancel && (
            <motion.div
              whileTap={{ scale: 0.95 }}
              transition={{ duration: 0.1 }}
            >
              <Button
                variant="outline"
                className="border-[#7A7A7A] text-[#F64C4C] hover:bg-[#404040] h-10"
                onClick={onCancel}
                disabled={isLoading === "cancel"}
              >
                {isLoading === "cancel" ? (
                  <svg
                    className="animate-spin h-4 w-4 mr-2"
                    viewBox="0 0 24 24"
                  >
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                      fill="none"
                    />
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8v8z"
                    />
                  </svg>
                ) : (
                  <CircleAlert size={16} className="mr-2" />
                )}
                {isLoading === "cancel" ? "Cancelling..." : "Cancel escrow"}
              </Button>
            </motion.div>
          )}
          <div className="flex items-center gap-3 ml-auto">
            <CircleAlert size={20} className="text-[#FEB64D]" />
            <Typography variant="small" className="text-white">
              This action cannot be undone.
            </Typography>
          </div>
        </motion.div>
      )}

    </div>
  );
} 