import { Resend } from 'resend'
import { generateEmailFooter } from './layout/generateEmailFooter'
import { generateEmailHeader } from './layout/generateEmailHeader'
import { generateContentCard } from './utils/generateContentCard'
import { generateEmailContainer } from './utils/generateEmailContainer'
import { generateFieldDisplay } from './utils/generateFieldDisplay'

export class EmailService {
  private readonly supportEmail = process.env.NEXT_RESEND_DEV_EMAIL
  private readonly fromEscrow = process.env.NEXT_RESEND_FROM_ESCROW || 'SplitSafe Escrow <onboarding@resend.dev>'
  private readonly fromGeneric = process.env.NEXT_RESEND_FROM_GENERIC || 'SplitSafe <onboarding@resend.dev>'
  private readonly fromFeedback = process.env.NEXT_RESEND_FROM_FEEDBACK || 'SplitSafe Feedback <onboarding@resend.dev>'
  private readonly fromSupport = process.env.NEXT_RESEND_FROM_SUPPORT || 'SplitSafe Support <onboarding@resend.dev>'
  private resend: Resend | undefined

  constructor() {
    const apiKey = process.env.NEXT_RESEND_API_KEY
    if (apiKey) {
      this.resend = new Resend(apiKey)
    } else {
    }
  }

  async sendSupportEmail(formData: {
    name: string
    email: string
    subject: string
    message: string
  }): Promise<boolean> {
    try {
      // Check if API key is available
      if (!process.env.NEXT_RESEND_API_KEY || !this.resend) {
        return true // Return true so user thinks it was sent
      }

      const emailContent = this.formatSupportEmail(formData)

      // Send email using Resend (only if we have a valid instance)
      if (!this.resend) {
        return true
      }

      // Send to the support email
      const actualRecipient = this.supportEmail || 'support@example.com'

      const { error } = await this.resend.emails.send({
        from: this.fromSupport, // Using Resend's default domain unless overridden
        to: [actualRecipient],
        subject: `SplitSafe Support: ${formData.subject}`,
        html: this.formatSupportEmailHTMLNew(formData),
        text: emailContent,
        replyTo: formData.email,
      })

      if (error) {
        console.error('Resend error:', error)
        // If it's a domain/recipient restriction, fall back to logging
        if (error && typeof error === 'object' && 'statusCode' in error && error.statusCode === 403) {
          return true
        }
        return false
      }

      return true
    } catch (error) {
      console.error('Error sending support email:', error)
      return false
    }
  }

  private formatSupportEmail(formData: {
    name: string
    email: string
    subject: string
    message: string
  }): string {
    return `
New Support Request from SplitSafe

Contact Information:
Name: ${formData.name}
Email: ${formData.email}

Subject: ${formData.subject}

Message:
${formData.message}

---
This message was sent from the SplitSafe contact form.
Timestamp: ${new Date().toISOString()}
User Agent: ${typeof window !== 'undefined' ? window.navigator.userAgent : 'Server-side'}
    `.trim()
  }

  async sendFeedbackEmail(feedbackData: {
    name: string
    email: string
    rating: number
    message: string
    userAgent?: string
    timestamp?: string
  }): Promise<boolean> {
    try {
      // Check if API key is available
      if (!process.env.NEXT_RESEND_API_KEY || !this.resend) {
        return true // Return true so user thinks it was sent
      }

      const emailContent = this.formatFeedbackEmail(feedbackData)

      // Send email using Resend (only if we have a valid instance)
      if (!this.resend) {
        return true
      }

      // Use the main email address for all feedback
      const mainEmail = this.supportEmail
      
      // Auto-generate subject based on rating and name
      const stars = '★'.repeat(feedbackData.rating) + '☆'.repeat(5 - feedbackData.rating)
      const autoGeneratedSubject = `SplitSafe Feedback from ${feedbackData.name} (${stars} ${feedbackData.rating}/5)`
      
      // Send to the main email address
      const recipients = [mainEmail || 'support@example.com']
      const subject = autoGeneratedSubject

      const { error } = await this.resend.emails.send({
        from: this.fromFeedback, // Using Resend's default domain unless overridden
        to: recipients,
        subject: subject,
        html: this.formatFeedbackEmailHTML(feedbackData),
        text: emailContent,
        replyTo: feedbackData.email,
      })

      if (error) {
        console.error('Resend error:', error)
        // If it's a domain/recipient restriction, fall back to logging
        if (error && typeof error === 'object' && 'statusCode' in error && error.statusCode === 403) {
          return true
        }
        return false
      }

      console.log(`Feedback email sent successfully to: ${recipients.join(', ')}`)
      return true
    } catch (error) {
      console.error('Error sending feedback email:', error)
      return false
    }
  }

  async sendMilestoneEmail(
    to: string,
    subject: string,
    html: string
  ): Promise<boolean> {
    try {
      // Check if API key is available
      if (!process.env.NEXT_RESEND_API_KEY || !this.resend) {
        return true // Return true so user thinks it was sent
      }

      // Send email using Resend (only if we have a valid instance)
      if (!this.resend) {
        return true
      }

      // Send to the specified recipient
      const actualRecipient = to
      const actualSubject = subject

      const { error } = await this.resend.emails.send({
        from: this.fromGeneric,
        to: [actualRecipient],
        subject: actualSubject,
        html,
      })

      if (error) {
        console.error('Resend error:', error)
        // If it's a domain/recipient restriction, fall back to logging
        if (error && typeof error === 'object' && 'statusCode' in error && error.statusCode === 403) {
          return true
        }
        return false
      }

      return true
    } catch (error) {
      console.error('Error sending milestone email:', error)
      return false
    }
  }

  async sendEscrowEmail(
    to: string,
    subject: string,
    html: string
  ): Promise<boolean> {
    try {
      if (!process.env.NEXT_RESEND_API_KEY || !this.resend) {
        return true
      }

      if (!this.resend) {
        return true
      }

      // Optionally send a debug copy to the dev email
      const devEmail = this.supportEmail
      const recipients = devEmail ? [to, devEmail] : [to]
      const actualSubject = devEmail ? `[DEBUG COPY] ${subject}` : subject

      const { error } = await this.resend.emails.send({
        from: this.fromEscrow,
        to: recipients,
        subject: actualSubject,
        html,
      })

      if (error) {
        console.error('Resend error:', error)
        if (error && typeof error === 'object' && 'statusCode' in error && error.statusCode === 403) {
          return true
        }
        return false
      }

      return true
    } catch (error) {
      console.error('Error sending escrow email:', error)
      return false
    }
  }

  async sendVoucherEmail(
    to: string,
    subject: string,
    html: string
  ): Promise<boolean> {
    try {
      if (!process.env.NEXT_RESEND_API_KEY || !this.resend) {
        return true
      }

      if (!this.resend) {
        return true
      }

      const { error } = await this.resend.emails.send({
        from: this.fromGeneric.replace('SplitSafe', 'SplitSafe Voucher'),
        to: [to],
        subject,
        html,
      })

      if (error) {
        console.error('Resend error:', error)
        if (error && typeof error === 'object' && 'statusCode' in error && error.statusCode === 403) {
          return true
        }
        return false
      }

      return true
    } catch (error) {
      console.error('Error sending voucher email:', error)
      return false
    }
  }

  private formatFeedbackEmail(feedbackData: {
    name: string
    email: string
    rating: number
    message: string
    userAgent?: string
    timestamp?: string
  }): string {
    const stars = '★'.repeat(feedbackData.rating) + '☆'.repeat(5 - feedbackData.rating)

    return `
New Feedback from SplitSafe

Contact Information:
Name: ${feedbackData.name}
Email: ${feedbackData.email}

Rating: ${stars} (${feedbackData.rating}/5)

Message:
${feedbackData.message}

---
This feedback was sent from the SplitSafe feedback form.
Timestamp: ${feedbackData.timestamp || new Date().toISOString()}
User Agent: ${feedbackData.userAgent || 'Unknown'}
    `.trim()
  }

  private formatFeedbackEmailHTML(feedbackData: {
    name: string
    email: string
    rating: number
    message: string
    userAgent?: string
    timestamp?: string
  }): string {
    const stars = '★'.repeat(feedbackData.rating) + '☆'.repeat(5 - feedbackData.rating)

    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>SplitSafe Feedback</title>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; }
    .container { width: 80%; max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: #FEB64D; color: #000; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
    .content { background: #f9f9f9; padding: 20px; border-radius: 0 0 8px 8px; }
    .field { margin-bottom: 15px; }
    .label { font-weight: bold; color: #555; }
    .value { margin-top: 5px; }
    .rating { color: #FEB64D; font-size: 18px; }
    .category { background: #e8f4fd; padding: 8px 12px; border-radius: 4px; display: inline-block; }
    .message-box { background: white; padding: 15px; border-left: 4px solid #FEB64D; margin: 15px 0; }
    .footer { margin-top: 20px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
    
    /* Mobile Responsive Styles */
    @media only screen and (max-width: 600px) {
      .container { 
        width: 95% !important; 
        padding: 10px !important; 
        margin: 0 auto !important;
      }
      .header { 
        padding: 15px !important; 
        border-radius: 4px 4px 0 0 !important;
      }
      .header h1 { 
        font-size: 20px !important; 
        margin: 0 !important;
      }
      .content { 
        padding: 15px !important; 
        border-radius: 0 0 4px 4px !important;
      }
      .field { 
        margin-bottom: 12px !important; 
      }
      .label { 
        font-size: 14px !important; 
      }
      .value { 
        font-size: 14px !important; 
      }
      .rating { 
        font-size: 16px !important; 
      }
      .message-box { 
        padding: 12px !important; 
        margin: 12px 0 !important;
        font-size: 14px !important;
      }
      .footer { 
        font-size: 11px !important; 
        padding-top: 12px !important;
      }
    }
    
    /* Extra small screens */
    @media only screen and (max-width: 480px) {
      .container { 
        width: 98% !important; 
        padding: 8px !important; 
      }
      .header { 
        padding: 12px !important; 
      }
      .header h1 { 
        font-size: 18px !important; 
      }
      .content { 
        padding: 12px !important; 
      }
      .message-box { 
        padding: 10px !important; 
        font-size: 13px !important;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>SplitSafe Feedback</h1>
    </div>
    <div class="content">
      <div class="field">
        <div class="label">Name:</div>
        <div class="value">${feedbackData.name}</div>
      </div>
      <div class="field">
        <div class="label">Email:</div>
        <div class="value"><a href="mailto:${feedbackData.email}">${feedbackData.email}</a></div>
      </div>
      <div class="field">
        <div class="label">Rating:</div>
        <div class="value rating">${stars} (${feedbackData.rating}/5)</div>
      </div>
      <div class="field">
        <div class="label">Message:</div>
        <div class="message-box">${feedbackData.message.replace(/\n/g, '<br>')}</div>
      </div>
      <div class="footer">
        <p>This feedback was sent from the SplitSafe feedback form.</p>
        <p>Timestamp: ${feedbackData.timestamp || new Date().toISOString()}</p>
      </div>
    </div>
  </div>
</body>
</html>
    `.trim()
  }

  private formatSupportEmailHTML(formData: {
    name: string
    email: string
    subject: string
    message: string
  }): string {
    return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>SplitSafe Support Request</title>
  <style>
    body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
    .container { width: 100%; margin: 0; padding: 20px; }
    .header { background: #FEB64D; color: #000; padding: 20px; text-align: center; border-radius: 8px 8px 0 0; }
    .content { background: #f9f9f9; padding: 20px; border-radius: 0 0 8px 8px; }
    .field { margin-bottom: 15px; }
    .label { font-weight: bold; color: #555; }
    .value { margin-top: 5px; }
    .message-box { background: white; padding: 15px; border-left: 4px solid #FEB64D; margin: 15px 0; }
    .footer { margin-top: 20px; padding-top: 15px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>SplitSafe Support Request</h1>
    </div>
    <div class="content">
      <div class="field">
        <div class="label">Name:</div>
        <div class="value">${formData.name}</div>
      </div>
      <div class="field">
        <div class="label">Email:</div>
        <div class="value"><a href="mailto:${formData.email}">${formData.email}</a></div>
      </div>
      <div class="field">
        <div class="label">Subject:</div>
        <div class="value">${formData.subject}</div>
      </div>
      <div class="field">
        <div class="label">Message:</div>
        <div class="message-box">${formData.message.replace(/\n/g, '<br>')}</div>
      </div>
      <div class="footer">
        <p>This message was sent from the SplitSafe contact form.</p>
        <p>Timestamp: ${new Date().toISOString()}</p>
      </div>
    </div>
  </div>
</body>
</html>
    `.trim()
  }

  private formatSupportEmailHTMLNew(formData: {
    name: string
    email: string
    subject: string
    message: string
  }): string {
    const header = generateEmailHeader('Support Request')

    const detailsContent = `
      <h2 style="color: #333; margin-top: 0;">Contact Details</h2>
      
      ${generateFieldDisplay('Name', formData.name)}
      ${generateFieldDisplay('Email', formData.email)}
      ${generateFieldDisplay('Subject', formData.subject)}
      
      <h3 style="color: #333; margin-top: 25px;">Message</h3>
      <div style="
        background: white; 
        padding: 15px; 
        border-left: 4px solid #FEB64D; 
        margin: 15px 0;
        border-radius: 4px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
      ">
        ${formData.message.replace(/\n/g, '<br>')}
      </div>
      
      <div style="
        background: #e8f4fd; 
        padding: 12px; 
        border-radius: 4px; 
        margin: 20px 0;
        border-left: 4px solid #007AFF;
      ">
        <strong>📧 Support Request</strong><br>
        This message was sent from the SplitSafe contact form.
      </div>
    `

    const content = generateContentCard(detailsContent)
    const footer = generateEmailFooter()

    return generateEmailContainer(header + content + footer)
  }
}
