// Contacts module constants
import { DIALOG_DESCRIPTIONS, DIALOG_TITLES, ERROR_MESSAGES, FORM_CONSTRAINTS, PLACEHOLDERS, SUCCESS_MESSAGES, UI_SIZES } from '../shared.constants';

// Re-export shared constants with module-specific names
export const CONTACT_CONSTRAINTS = {
  NICKNAME: FORM_CONSTRAINTS.NICKNAME,
  PRINCIPAL_ID: FORM_CONSTRAINTS.PRINCIPAL_ID,
} as const;

export const CONTACT_UI = {
  AVATAR_SIZE: UI_SIZES.AVATAR.MEDIUM,
  PRINCIPAL_TRUNCATE_LENGTH: UI_SIZES.TRUNCATE.PRINCIPAL,
  ID_DISPLAY_LENGTH: UI_SIZES.TRUNCATE.ID,
} as const;

export const CONTACT_MESSAGES = {
  ADD_SUCCESS: SUCCESS_MESSAGES.CREATE,
  UPDATE_SUCCESS: SUCCESS_MESSAGES.UPDATE,
  REMOVE_SUCCESS: SUCCESS_MESSAGES.DELETE,
  ADD_ERROR: ERROR_MESSAGES.CREATE,
  UPDATE_ERROR: ERROR_MESSAGES.UPDATE,
  REMOVE_ERROR: ERROR_MESSAGES.DELETE,
  LOAD_ERROR: ERROR_MESSAGES.LOAD,
  SEARCH_PLACEHOLDER: PLACEHOLDERS.SEARCH,
  NO_CONTACTS: 'No contacts found.',
  NO_SEARCH_RESULTS: 'No contacts found matching your search.',
} as const;

export const CONTACT_DIALOG = {
  ADD_TITLE: DIALOG_TITLES.ADD,
  UPDATE_TITLE: DIALOG_TITLES.UPDATE,
  REMOVE_TITLE: DIALOG_TITLES.DELETE,
  ADD_DESCRIPTION: 'Add a new trusted contact for escrow transactions',
  UPDATE_DESCRIPTION: 'Update the contact information',
  REMOVE_DESCRIPTION: DIALOG_DESCRIPTIONS.DELETE_CONFIRM,
} as const;
